### ISSUE TITLE
WebdriverAgent is not  install automatically on iOS device

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-agent#147]

**Comment by namilkimfree** [comment]
IOS 15.0 

Appium log 


goroutine 1 [running]:
github.com/danielpaulus/go-ios/ios/instruments.DeviceInfoService.ProcessList({0xc0001ab2c0, 0xc000699540})
        /home/runner/work/go-ios/go-ios/ios/instruments/processlist.go:26 +0x137
main.Main()
        /home/runner/work/go-ios/go-ios/main.go:493 +0x1551
main.main()
        /home/runner/work/go-ios/go-ios/main.go:46 +0x17
[21/11/2022 20:48:00] Starting WebDriverAgent application on port 8100
detecting WDA_HOST ip address...
attempt 1
attempt 2
attempt 3
attempt 4
attempt 5
attempt 6
attempt 7
attempt 8
attempt 9
attempt 10
attempt 11
attempt 12
attempt 13
attempt 14
attempt 15
attempt 16
attempt 17
attempt 18
attempt 19
attempt 20
attempt 21
attempt 22
attempt 23
attempt 24
attempt 25
attempt 26
attempt 27
attempt 28
attempt 29
attempt 30
ERROR! Unable to parse WDA_HOST ip from log file!
{"bundleid":"com.webstf.WebDriverAgentRunner","level":"info","msg":"Running wda","testbundleid":"com.webstf.WebDriverAgentRunner","time":"2022-11-21T20:48:00-08:00","xctestconfig":"WebDriverAgentRunner.xctest"}
{"error":"Did not find AppInfo for 'com.webstf.WebDriverAgentRunner' on device. Is it installed?","level":"fatal","msg":"Failed running WDA","time":"2022-11-21T20:48:00-08:00"}
Detected WDA_HOST ip:
WDA_PORT=8100
[21/11/2022 20:48:30] Starting WebDriverAgent 1st session
WDA session response:
bundleId:
sessionId:
[21/11/2022 20:48:30] Activating springboard app forcibly
[21/11/2022 20:48:31] Stopping 1st default WebDriverAgent session
sessionId:

Connecting to  8101 using netcat...
no port[s] to connect to
netcat connection is closed.
[21/11/2022 20:48:31] Killing existing WebDriverAgent application if any
{
  "capabilities":
      [
        {
          "maxInstances": 1,
          "deviceName": "iPhone_13_Pro_Max",
          "deviceType": "Phone",
          "platformName":"ios",
          "platformVersion":"15.0",
          "udid": "00008110001859D1022A801E",
          "adb_port": 7432,
          "proxy_port": 7433,
          "automationName": "XCUITest"
        }
      ],
  "configuration":
  {
    "proxy": "com.zebrunner.mcloud.grid.MobileRemoteProxy",
    "url":"http://webstf-provider.nmn.io:7431/wd/hub",
    "host": "webstf-provider.nmn.io",
    "port": 7431,
    "hubHost": "webstf.nmn.io",
    "hubPort": 4446,
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "cleanUpCycle": 5000,
    "timeout": 180,
    "browserTimeout": 0,
    "nodeStatusCheckTimeout": 5000,
    "nodePolling": 5000,
    "role": "node",
    "unregisterIfStillDownAfter": 60000,
    "downPollingLimit": 2,
    "debug": false,
    "servlets" : [],
    "withoutServlets": [],
    "custom": {}
  }
}
{
 "udid":"00008110001859D1022A801E",
 "mjpegServerPort": 8101,
 "clearSystemFiles": "false",
 "webDriverAgentUrl":"http://:8100",
 "preventWDAAttachments": "true",
 "simpleIsVisibleCheck": "true",
 "wdaLocalPort": "8100",
 "platformVersion": "15.0",
 "automationName":"XCUITest",
 "platformName": "ios",
 "deviceName": "iPhone_13_Pro_Max",
 "provider": "mcloud",
 "enableVideo": "true",
 "enableLog": "true",
 "enableVnc": "false"
}
'/opt/mcloud/appium-patch.sh' -> '/usr/lib/node_modules/appium/appium-patch.sh' (backup: '/usr/lib/node_modules/appium/appium-patch.sh.~2~')
'/opt/mcloud/build/lib/grid-register.js' -> '/usr/lib/node_modules/appium/build/lib/grid-register.js' (backup: '/usr/lib/node_modules/appium/build/lib/grid-register.js.~3~')
'/opt/mcloud/node_modules/appium-base-driver/build/lib/basedriver/commands/session.js' -> '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/commands/session.js' (backup: '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/commands/session.js.~3~')
'/opt/mcloud/node_modules/appium-base-driver/build/lib/basedriver/driver.js' -> '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/driver.js' (backup: '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/driver.js.~3~')
'/opt/mcloud/node_modules/appium-base-driver/build/lib/basedriver/helpers.js' -> '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/helpers.js' (backup: '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/helpers.js.~3~')
'/opt/mcloud/node_modules/appium-base-driver/build/lib/basedriver/mcloud-utils.js' -> '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/mcloud-utils.js' (backup: '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/mcloud-utils.js.~2~')
'/opt/mcloud/node_modules/appium-base-driver/build/lib/protocol/protocol.js' -> '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/protocol/protocol.js' (backup: '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/protocol/protocol.js.~3~')
'/opt/mcloud/node_modules/appium-base-driver/build/lib/protocol/routes.js' -> '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/protocol/routes.js' (backup: '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/protocol/routes.js.~3~')
'/opt/mcloud/node_modules/appium-base-driver-7_10_0.diff' -> '/usr/lib/node_modules/appium/node_modules/appium-base-driver-7_10_0.diff' (backup: '/usr/lib/node_modules/appium/node_modules/appium-base-driver-7_10_0.diff.~2~')
'/opt/mcloud/node_modules/appium-xcuitest-driver/build/lib/ios-deploy.js' -> '/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver/build/lib/ios-deploy.js' (backup: '/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver/build/lib/ios-deploy.js.~3~')
'/opt/mcloud/node_modules/appium-xcuitest-driver-3_53_1.diff' -> '/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver-3_53_1.diff' (backup: '/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver-3_53_1.diff.~2~')
xvfb-run appium --log-no-colors --log-timestamp --log /var/log/appium.log --session-override --nodeconfig /root/nodeconfig.json --default-capabilities /root/defaultcapabilities.json --relaxed-security --allow-insecure chromedriver_autodownload
[info] [AppiumEntryPoint] registering upload method on SIGTERM
[info] [AppiumEntryPoint] waiting until SIGTERM received
Exit status: 1


device log

{"deviceList":["00008110001859D1022A801E"]}
Waiting until WDA settings appear 1 sec
Waiting until WDA settings appear 2 sec
Waiting until WDA settings appear 3 sec
Waiting until WDA settings appear 4 sec
Waiting until WDA settings appear 5 sec
Waiting until WDA settings appear 6 sec
Waiting until WDA settings appear 7 sec
Waiting until WDA settings appear 8 sec
Waiting until WDA settings appear 9 sec
Waiting until WDA settings appear 10 sec
Waiting until WDA settings appear 11 sec
Waiting until WDA settings appear 12 sec
Waiting until WDA settings appear 13 sec
Waiting until WDA settings appear 14 sec
Waiting until WDA settings appear 15 sec
Waiting until WDA settings appear 16 sec
Waiting until WDA settings appear 17 sec
Waiting until WDA settings appear 18 sec
Waiting until WDA settings appear 19 sec
Waiting until WDA settings appear 20 sec
Waiting until WDA settings appear 21 sec
Waiting until WDA settings appear 22 sec
Waiting until WDA settings appear 23 sec
Waiting until WDA settings appear 24 sec
Waiting until WDA settings appear 25 sec
Waiting until WDA settings appear 26 sec
Waiting until WDA settings appear 27 sec
Waiting until WDA settings appear 28 sec
Waiting until WDA settings appear 29 sec
Waiting until WDA settings appear 30 sec
Waiting until WDA settings appear 31 sec
Waiting until WDA settings appear 32 sec
Waiting until WDA settings appear 33 sec
Waiting until WDA settings appear 34 sec
Waiting until WDA settings appear 35 sec
Waiting until WDA settings appear 36 sec
Waiting until WDA settings appear 37 sec
Waiting until WDA settings appear 38 sec
Waiting until WDA settings appear 39 sec
Waiting until WDA settings appear 40 sec
export WDA_HOST=
export WDA_PORT=8100
export MJPEG_PORT=8101
export PLATFORM_VERSION=15.0
declare -x DEBIAN_FRONTEND="noninteractive"
declare -x DEVICE_UDID="00008110001859D1022A801E"
declare -x HOME="/root"
declare -x HOSTNAME="b92f31223bfd"
declare -x MJPEG_PORT="8101"
declare -x NODE_TLS_REJECT_UNAUTHORIZED="0"
declare -x OLDPWD
declare -x PATH="/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PLATFORM_NAME="ios"
declare -x PLATFORM_VERSION="15.0"
declare -x PUBLIC_IP_PORT="443"
declare -x PUBLIC_IP_PROTOCOL="https"
declare -x PWD="/opt"
declare -x RETHINKDB_PORT_28015_TCP="tcp://webstf.nmn.io:28015"
declare -x SHLVL="1"
declare -x STF_PROVIDER_ADB_HOST="appium"
declare -x STF_PROVIDER_ADB_PORT="5037"
declare -x STF_PROVIDER_APPIUM_PORT="7431"
declare -x STF_PROVIDER_BOOT_COMPLETE_TIMEOUT="60000"
declare -x STF_PROVIDER_CLEANUP="false"
declare -x STF_PROVIDER_CONNECT_PUSH="tcp://webstf.nmn.io:7270"
declare -x STF_PROVIDER_CONNECT_SUB="tcp://webstf.nmn.io:7250"
declare -x STF_PROVIDER_DEVICE_NAME="iPhone_13_Pro_Max"
declare -x STF_PROVIDER_GROUP_TIMEOUT="3600"
declare -x STF_PROVIDER_HEARTBEAT_INTERVAL="10000"
declare -x STF_PROVIDER_HOST="webstf-provider.nmn.io"
declare -x STF_PROVIDER_LOCK_ROTATION="false"
declare -x STF_PROVIDER_MAX_PORT="7440"
declare -x STF_PROVIDER_MIN_PORT="7434"
declare -x STF_PROVIDER_MUTE_MASTER="never"
declare -x STF_PROVIDER_NAME="mcloud-android-ios"
declare -x STF_PROVIDER_PUBLIC_IP="webstf.nmn.io"
declare -x STF_PROVIDER_SCREEN_JPEG_QUALITY="30"
declare -x STF_PROVIDER_SCREEN_PING_INTERVAL="30000"
declare -x STF_PROVIDER_SCREEN_RESET="false"
declare -x STF_PROVIDER_VNC_INITIAL_SIZE="600x800"
declare -x STF_PROVIDER_VNC_PORT="5900"
declare -x WDA_ENV="/opt/zebrunner/wda-00008110001859D1022A801E.env"
declare -x WDA_HOST=""
declare -x WDA_LOG_FILE="/opt/zebrunner/wda.log"
declare -x WDA_PORT="8100"
declare -x WDA_WAIT_TIMEOUT="180"
declare -x ZMQ_TCP_KEEPALIVE="1"
declare -x ZMQ_TCP_KEEPALIVE_IDLE="600"
2022-11-22T04:47:45.272Z INF/db 73 [00008110001859D1022A801E] Connecting to webstf.nmn.io:28015
2022-11-22T04:47:45.277Z INF/device:support:push 73 [00008110001859D1022A801E] Ios device sending output to "tcp://webstf.nmn.io:7270"
2022-11-22T04:47:45.279Z INF/ios-device 73 [00008110001859D1022A801E] Preparing device options:  {
  serial: '00008110001859D1022A801E',
  provider: 'mcloud-android-ios',
  publicIp: 'webstf.nmn.io',
  endpoints: {
    sub: [ 'tcp://webstf.nmn.io:7250' ],
    push: [ 'tcp://webstf.nmn.io:7270' ],
    appDealer: [ 'tcp://stf-triproxy-app:7160' ],
    devDealer: [ 'tcp://stf-triproxy-dev:7260' ]
  },
  groupTimeout: 3600000,
  storageUrl: 'https://webstf.nmn.io:443/',
  adbHost: '127.0.0.1',
  adbPort: 5037,
  screenJpegQuality: 30,
  screenPingInterval: 30000,
  screenPort: 7434,
  screenWsUrlPattern: 'wss://webstf.nmn.io:443/d/webstf-provider.nmn.io/00008110001859D1022A801E/7434/',
  connectUrlPattern: 'webstf-provider.nmn.io:<%= publicPort %>',
  connectPort: 8101,
  wdaHost: '',
  wdaPort: 8100,
  vncInitialSize: [ 600, 800 ],
  heartbeatInterval: 10000,
  bootCompleteTimeout: 60000,
  muteMaster: 'never',
  lockRotation: false,
  cleanup: true,
  screenReset: true,
  udidStorage: false,
  iproxy: false,
  host: 'webstf-provider.nmn.io',
  appiumPort: 7431,
  deviceName: 'iPhone_13_Pro_Max',
  deviceType: 'phone'
}
2022-11-22T04:47:45.488Z INF/device:support:sub 73 [00008110001859D1022A801E] Receiving input from "tcp://webstf.nmn.io:7250"
2022-11-22T04:47:45.489Z INF/device:support:sub 73 [00008110001859D1022A801E] Subscribing to permanent channel "*ALL"
2022-11-22T04:47:45.491Z INF/device:plugins:solo 73 [00008110001859D1022A801E] Subscribing to permanent channel "d9hdx7/sPvnTPDSsZnImlV3xH4M="
2022-11-22T04:47:45.493Z INF/wdaClient 73 [00008110001859D1022A801E] WdaClient.js initializing...
2022-11-22T04:47:45.501Z INF/device:info 73 [00008110001859D1022A801E] device.name: iPhone_13_Pro_Max
2022-11-22T04:47:45.506Z INF/util:lifecycle 73 [00008110001859D1022A801E] Winding down for graceful exit, with optional error :  Error: connect ECONNREFUSED 127.0.0.1:8101
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8101
}
2022-11-22T04:47:45.509Z FTL/util:lifecycle 73 [00008110001859D1022A801E] Shutting down due to fatal error with optional error :  Error: connect ECONNREFUSED 127.0.0.1:8101
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8101
}
Exit status: 1
